#!/usr/bin/env bash
set -e
set -x

SUPPORTED_ENVIRONMENTS=$(find config -type f -name "infrastructure_config*" \
  -exec sh -c "echo {} | cut -f2 -d '.'" \;)

usage() {
  printf "deploy.sh [target_environment]\n"
  printf "Deploys infrastructure for carlosnunez.me\n\n"
  printf "  target_environment: The environment to deploy onto. \
Supported environments: [${SUPPORTED_ENVIRONMENTS}]\n\n"
}

is_env_supported() {
  env_to_check="$1"
  supported_envs="$2"
  matching_envs_found=$(echo "$supported_envs" | grep "${env_to_check}")
  if [ "$matching_envs_found" != "" ]
  then
    return 0
  else
    return 1
  fi
}

NUMBER_OF_ARGS_EXPECTED=1
if [ "$#" != "$NUMBER_OF_ARGS_EXPECTED" ]
then
  usage
  exit 1
fi

target_env=$1
if ! is_env_supported $target_env $SUPPORTED_ENVIRONMENTS
then
  printf "ERROR: '${target_env}' not found in '${SUPPORTED_ENVIRONMENTS}'\n"
  usage
  exit 1
fi

for command in 'ruby --version' 'which gem'
do
  ruby_installation_check_result=$(eval "$command" 2>/dev/null; echo $?)
  if [ "$ruby_installation_check_result" != "0" ]
  then
    printf "ERROR: Installation check [$command] failed. Ensure that Ruby and \
gem is installed correctly.\n"
    exit 1
  fi
done

which bundle 2>/dev/null || {
  printf "INFO: Bundler not found. Installing Bundler.\n"
  gem install bundler
}

TARGET_ENVIRONMENT=$target_env bundle exec rake

