version: '3'
services:
  jenkins-master:
    image: jenkinsci/jenkins:lts
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
      - jenkins-master-data-service:/var/jenkins_home
    env_file:
      - .env.jenkins-master
    external_links:
      - jenkins-worker
      - pipeline-runner
    user: jenkins
  jenkins-master-data-service:
    image: busybox
    volumes:
      - $PWD/config/jenkins/jenkins_home:/var/jenkins_home
    command: "chown jenkins:jenkins /var/jenkins_home"
  jenkins-worker:
    image: jenkinsci/jnlp-slave
    environment:
      JENKINS_URL: 'http://jenkins-master:8080'
      JENKINS_SECRET: 'aaa12345'
      JENKINS_AGENT_NAME: 'jenkins-worker'
    external_links:
      - jenkins-master
    depends_on:
      - jenkins-master
    healthcheck:
      test: curl -f http://jenkins-master:8080
      interval: 30s
      timeout: 2s
      retries: 15
  pipeline-runner:
    build:
      context: .
      dockerfile: Dockerfile-pipeline_runner
    image: pipeline-runner
    depends_on:
      - jenkins-master
    healthcheck:
      test: curl -f http://jenkins-master:8080
      interval: 30s
      timeout: 2s
      retries: 15
volumes:
  jenkins-master-data-service:
