FROM jenkinsci/jenkins
MAINTAINER Carlos Nunez <dev@carlosnunez.me>

USER root
RUN apt-get update
RUN \
  for package in python python-setuptools python-dev build-essential; \
  do \
    apt-get -y install $package; \
  done;
RUN easy_install pip
RUN pip install awscli
deb http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu trusty main
deb-src http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu trusty main
RUN apt-get -y update
RUN apt-get -y install ruby2.4 ruby2.4-dev
USER jenkins

COPY files/jenkins/config.xml /usr/share/jenkins/ref/config.xml.override
COPY files/jenkins/create_admin_user.groovy /usr/share/jenkins/ref/init.groovy.d/create_admin_user.groovy
COPY files/jenkins/jobs/deploy-infrastructure-seed-job.xml /usr/share/jenkins/ref/jobs/deploy-infrastructure-carlosnunez.me/config.xml

RUN install-plugins.sh workflow-aggregator job-dsl git
