FROM jenkinsci/jenkins
MAINTAINER Carlos Nunez <dev@carlosnunez.me>

USER root
RUN apt-get update
RUN \
  for package in python python-setuptools python-dev build-essential; \
  do \
    apt-get -y install $package; \
  done;
RUN easy_install pip
RUN pip install awscli
RUN \
	gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 && \
	\curl -sSL https://get.rvm.io | bash -s stable --ruby=2.4
USER jenkins

COPY files/jenkins/config.xml /usr/share/jenkins/ref/config.xml.override
COPY files/jenkins/create_admin_user.groovy /usr/share/jenkins/ref/init.groovy.d/create_admin_user.groovy
COPY files/jenkins/jobs/deploy-infrastructure-seed-job.xml /usr/share/jenkins/ref/jobs/deploy-infrastructure-carlosnunez.me/config.xml

RUN install-plugins.sh workflow-aggregator job-dsl git
