version: '2'
services:
  jenkins-master:
    image: jenkinsci/jenkins:lts
    ports:
      - "80:8080"
      - "50000:50000"
    volumes_from:
      - data_jenkins-master
    env_file:
      - .env.jenkins-master
    external_links:
      - jenkins-worker
      - pipeline-runner

  data_jenkins-master:
    image: busybox
    volumes:
      - $HOME/jenkins/.ssh
      - $PWD/config/jenkins/jenkins_home:/var/jenkins_home

  jenkins-worker:
    image: jenkinsci/jnlp-slave
    environment:
      JENKINS_URL: 'http://jenkins-master:8080'
      JENKINS_SECRET: 'aaa12345'
      JENKINS_AGENT_NAME: 'jenkins-worker'
    external_links:
      - jenkins-master

  pipeline-runner:
    build:
      context: .
      dockerfile: Dockerfile-pipeline_runner
    image: pipeline-runner
    external_links:
      - jenkins-master
