version: '3'
services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile-jenkins_master
    image: local_jenkins_master
    ports:
      - "80:8080"
    env_file:
      - .env.jenkins-master
  pipeline-runner:
    build:
      context: .
      dockerfile: Dockerfile-pipeline_runner
    image: pipeline-runner
    depends_on:
      - jenkins-master
    healthcheck:
      test: curl -f http://jenkins-master:8080/jobs/deploy-infrastructure-carlosnunez.me
      interval: 30s
      timeout: 2s
      retries: 15
