version: '3'
services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile-jenkins_master
    image: local_jenkins_master
    ports:
      - "80:8080"
    env_file:
      - .env.jenkins-master
  pipeline-runner:
    build:
      context: .
      dockerfile: Dockerfile-pipeline_runner
    image: pipeline-runner
    depends_on:
      - jenkins-master
    environment:
      - JENKINS_MASTER_HOSTNAME=jenkins-master
      - JENKINS_JOB_NAME=deploy-infrastructure-carlosnunez.me
      - JENKINS_USERNAME=admin
      - JENKINS_PASSWORD=password
      - WITHIN_DEPLOYMENT_CONTAINER=true
      - TARGET_ENVIRONMENT
    command: /tmp/deploy $TARGET_ENVIRONMENT
    healthcheck:
      test: nc -z $JENKINS_MASTER_HOSTNAME 8080
      interval: 5s
      timeout: 1m 
