FROM jenkinsci/jenkins
MAINTAINER Carlos Nunez <dev@carlosnunez.me>

COPY files/jenkins/config.xml /var/jenkins_home/config.xml
COPY files/jenkins/create_admin_user.groovy /usr/share/jenkins/ref/init.groovy.d/create_admin_user.groovy
COPY files/jenkins/jobs/deploy-infrastructure.xml /usr/share/jenkins/ref/jobs/deploy-infrastructure/config.xml

RUN install-plugins.sh workflow-aggregator job-dsl
