#!/bin/bash
maybe_op="${1}"
case $maybe_op in
  plan|destroy|apply)
    operation="${maybe_op}"
    ;;
  '')
    echo "ERROR: You must provide an operation to Terraform (plan, destroy or apply)."
    exit 1
    ;;
  *)
    echo "ERROR: Operation '${1}' is not supported."
    exit 1
    ;;
esac

environment=`echo ${@:0} | \
  grep '-environment=' | \
  sed 's/.*\-environment=\(.*\) .*/\1/' | \
  cut -f2 -d'='`

[ -z "$environment" ] && {
  echo "ERROR: Environment not specified."
  exit 1
}

var_files_arr=`find include/$environment/tfvars -type f | \
  while read file_path
  do
    echo "-var-file=${file_path}"
  done`

var_files=`echo "${var_files_arr}" | tr '\n' ' '`

command="terraform ${operation} ${var_files} ${@:3}"
echo "COMMAND: $command"
eval "${command}"
